# Generated by Django 5.0.6 on 2024-07-01 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_body_alter_task_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='body',
            new_name='description',
        ),
    ]
