# Generated by Django 5.0.6 on 2024-08-02 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0003_alter_status_options_alter_status_name'),
        ('tasks', '0007_rename_body_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status', to='statuses.status', verbose_name='Status'),
        ),
    ]
