name: run tests

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install poetry
          make install

      - name: Run code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DATABASE_URL: sqlite:///db.sqlite3
        with:
          coverageCommand: make test-coverage
          debug: true